name: Publish Release

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]

jobs:
  publish-release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
        
    - name: Run tests
      run: ./gradlew test
      
    - name: Publish release
      run: ./gradlew publishAggregationToCentralPortal
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
        signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}