name: Publish Snapshot

on:
  push:
    branches: [ develop ]

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Set snapshot version
      run: |
        VERSION=$(grep "version = " build.gradle | sed 's/version = "\(.*\)"/\1/')
        if [[ ! $VERSION == *"-SNAPSHOT" ]]; then
          sed -i "s/version = \"$VERSION\"/version = \"$VERSION-SNAPSHOT\"/" build.gradle
        fi
        
    - name: Run tests
      run: ./gradlew test
      
    - name: Publish snapshot
      run: ./gradlew publishAggregationToCentralPortalSnapshots
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
        signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}