name: Snapshot Release

on:
  push:
    branches: ['master']

jobs:
  build:
    name: Compile and Test code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        run: ./gradlew build --no-daemon

  publish:
    name: Publish Artifacts
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Publish with Gradle
        env:
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.PGP_SECRET }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PGP_PASSPHRASE }}
        run: ./gradlew -Psnapshot=false publishToSonatype --no-daemon

  increment:
    name: Increment Version
    needs: [publish]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Increment Version
        run: |
          git config --global user.email "sidhant92@hotmail.com"
          git config --global user.name "Sidhant Aggarwal"
          ./gradlew incrementVersion --versionIncrementType=PATCH --versionIncrementBranch=master
